"""Bring up Gemini 335 depth, calibrated static extrinsics, and 3D fusion."""

from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, IncludeLaunchDescription
from launch.conditions import IfCondition
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration, PathJoinSubstitution
from launch_ros.actions import Node
from launch_ros.parameter_descriptions import ParameterValue
from launch_ros.substitutions import FindPackageShare


def generate_launch_description():
    use_sim_time = LaunchConfiguration("use_sim_time")
    start_gemini = LaunchConfiguration("start_gemini")
    calibration_file = LaunchConfiguration("calibration_file")

    arguments = [
        DeclareLaunchArgument("use_sim_time", default_value="false"),
        DeclareLaunchArgument(
            "start_gemini",
            default_value="true",
            description="Start the in-workspace Orbbec Gemini 330-series driver",
        ),
        DeclareLaunchArgument(
            "calibration_file",
            default_value="/home/nvidia/fcr_calibration/sony_gemini_extrinsics.yaml",
            description="Schema-v2 file generated by stereo_calibrate.py",
        ),
        DeclareLaunchArgument(
            "fusion_params",
            default_value=PathJoinSubstitution(
                [FindPackageShare("perception_pkg"), "config", "depth_fusion_params.yaml"]
            ),
        ),
        DeclareLaunchArgument("gemini_serial_number", default_value=""),
        DeclareLaunchArgument("publish_debug_image", default_value="false"),
    ]

    gemini = IncludeLaunchDescription(
        PythonLaunchDescriptionSource(
            PathJoinSubstitution(
                [FindPackageShare("orbbec_camera"), "launch", "gemini_330_series.launch.py"]
            )
        ),
        launch_arguments={
            "camera_name": "camera",
            "serial_number": LaunchConfiguration("gemini_serial_number"),
            "enable_depth": "true",
            "enable_color": "true",
            "enable_point_cloud": "false",
            "enable_colored_point_cloud": "false",
            "depth_registration": "false",
        }.items(),
        condition=IfCondition(start_gemini),
    )

    extrinsics = Node(
        package="perception_pkg",
        executable="extrinsics_tf_publisher.py",
        name="sony_gemini_extrinsics_tf_publisher",
        output="screen",
        arguments=["--calibration", calibration_file],
        parameters=[{"use_sim_time": ParameterValue(use_sim_time, value_type=bool)}],
    )

    fusion = Node(
        package="perception_pkg",
        executable="depth_fusion_node",
        name="depth_fusion_node",
        output="screen",
        parameters=[
            LaunchConfiguration("fusion_params"),
            {
                "use_sim_time": ParameterValue(use_sim_time, value_type=bool),
                "debug.publish_image": ParameterValue(
                    LaunchConfiguration("publish_debug_image"), value_type=bool
                ),
            },
        ],
    )

    return LaunchDescription(arguments + [gemini, extrinsics, fusion])
